minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2201.5'
  - '@angular-devkit/core@22.1.5'
  - '@angular-devkit/schematics@22.1.5'
  - '@angular/build@22.1.5'
  - '@angular/cli@22.1.5'
  - '@schematics/angular@22.1.5'
