<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Blinky</Product>
    <Company>Blinky contributors</Company>
    <Copyright>Copyright 2026 Szymon Frankiewicz</Copyright>
    <Version>0.1.0</Version>
    <RepositoryUrl>https://github.com/franekSoftSF/blinky</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

</Project>
