<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Blinky.Contracts\Blinky.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Blinky.Domain\Blinky.Domain.csproj" />
    <ProjectReference Include="..\..\src\Blinky.Piv\Blinky.Piv.csproj" />
    <ProjectReference Include="..\..\src\Blinky.Infrastructure\Blinky.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\docker\postgres\001-schema.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>