using System.Text;

namespace Blinky.PaletteTool;

/// <summary>
/// Writes the palette out in the two shapes that draw it: CSS custom
/// properties for the Angular console and resource dictionaries for the WPF
/// tray UI.
/// </summary>
/// <remarks>
/// Generated rather than hand-kept, for the reason the database schema is:
/// two copies of the same fact drift, and the drift is invisible until
/// somebody looks at both at once. <c>PaletteFilesTests</c> fails the build
/// when a committed file stops matching what this would write.
/// </remarks>
public static class Generator
{
    private const string Banner =
        "Generated by tools/PaletteTool from Palette.cs. Do not edit by hand:\n" +
        "   dotnet run --project tools/PaletteTool";

    // The same thing for XAML, where that command cannot be written: an XML
    // comment may not contain two dashes in a row, and "--project" has two.
    private const string XamlBanner =
        "Generated by tools/PaletteTool from Palette.cs. Do not edit by hand;\n" +
        "run that tool again instead. CLAUDE.md has the command.";

    public static string Tokens()
    {
        var text = new StringBuilder();

        text.Append("/* ").Append(Banner.Replace("\n", "\n   ")).Append(" */\n\n");
        text.Append("/*\n")
            .Append(" * Every colour the console draws with, once. A rule that needs a colour\n")
            .Append(" * takes a token; a rule that carries a hex is a colour nobody can find\n")
            .Append(" * again, which is how this file came to exist - see 0099.\n")
            .Append(" */\n\n");

        text.Append(Block(":root,\nhtml[data-theme='dark']", Palette.Dark, "dark"));
        text.Append('\n');
        text.Append(Block("html[data-theme='light']", Palette.Light, "light"));

        return text.ToString();
    }

    public static string Theme(Palette palette)
    {
        // The keys the XAML already binds to, in the order the dictionaries
        // have always listed them. Renaming one means editing every view, so
        // the names stay even where the palette's own role reads better.
        (string Key, string Role)[] keys =
        [
            ("Panel", "panel"),
            ("PanelRaised", "panel-raised"),
            ("Divider", "border"),
            ("Text", "text"),
            ("TextMuted", "text-muted"),
            ("TextFaint", "text-faint"),
            ("Accent", "accent"),
            ("AccentText", "accent-text"),
            ("AccentSoft", "accent-soft"),
            ("OnAccent", "on-accent"),
            ("Warning", "warning"),
            ("WarningSoft", "warning-soft"),
            ("Danger", "danger"),
            ("Managed", "ok"),
            ("ManagedSoft", "ok-soft"),
            ("FieldBackground", "field"),
        ];

        var colours = palette.Roles.ToDictionary(role => role.Role, role => role.Colour);
        var text = new StringBuilder();

        text.Append("<ResourceDictionary xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"\n")
            .Append("                    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">\n\n");

        text.Append("    <!-- ").Append(XamlBanner.Replace("\n", "\n         ")).Append(" -->\n\n");

        text.Append("    <!-- The tray UI and the web console are the same product, so they are\n")
            .Append("         the same colours: this dictionary and frontend/src/tokens.scss come\n")
            .Append("         out of one Palette.cs. Both dictionaries define exactly the same\n")
            .Append("         keys - a key present in one and missing from the other is a XAML\n")
            .Append("         error that only appears after somebody switches theme, which is the\n")
            .Append("         worst time to find it. -->\n\n");

        text.Append("    <Color x:Key=\"BackgroundColour\">")
            .Append(colours["background"].Hex)
            .Append("</Color>\n");
        text.Append("    <SolidColorBrush x:Key=\"Background\" Color=\"{StaticResource BackgroundColour}\" />\n");

        foreach (var (key, role) in keys)
        {
            text.Append("    <SolidColorBrush x:Key=\"")
                .Append(key)
                .Append("\" Color=\"")
                .Append(colours[role].Hex)
                .Append("\" />\n");
        }

        text.Append("\n</ResourceDictionary>\n");

        return text.ToString();
    }

    private static string Block(string selector, Palette palette, string name)
    {
        var text = new StringBuilder();

        text.Append("/* palette:").Append(name).Append(" */\n");
        text.Append(selector).Append(" {\n");

        foreach (var (role, colour) in palette.Roles)
        {
            text.Append("  --bl-").Append(role).Append(": ").Append(colour.Hex.ToLowerInvariant()).Append(";\n");
        }

        // Two shades of the same surfaces, translucent, because the sidebar and
        // the panels sit over the background's gradient and hiding it entirely
        // flattens the page.
        text.Append("  --bl-panel-veil: ").Append(palette.Panel.Hex.ToLowerInvariant()).Append("db;\n");
        text.Append("  --bl-surface-veil: ").Append(palette.Surface.Hex.ToLowerInvariant()).Append("bb;\n");

        text.Append("  color-scheme: ").Append(name).Append(";\n");
        text.Append("}\n");
        text.Append("/* /palette:").Append(name).Append(" */\n");

        return text.ToString();
    }
}
