#!/usr/bin/env bash
#
# Blinky lab - give Samba's LDAP listener a certificate somebody can verify.
#
#     sudo bash samba-ldap-tls.sh                     # writes /tmp/ldap.csr
#     sudo bash samba-ldap-tls.sh --cert /tmp/ldap.crt --chain /tmp/chain.pem
#
# Run on the domain controller. Two passes, like blinky-samba-setup.sh: the
# first makes a key and a request, the second installs what came back.
#
# Why this is needed at all:
#
#   A provisioned Samba AD DC answers StartTLS on 389 with a certificate it
#   generated for itself, subject "Samba - temporary autogenerated HOST
#   certificate", signed by an equally temporary CA. Nothing anywhere can
#   verify it.
#
#   A client that checks refuses the connection. A client that does not check
#   is sending a bind password to whoever answered on that port. There is no
#   third option worth having, and turning TLS off is the second one with extra
#   steps.
#
#   What the refusal looks like is the reason this is worth a script: .NET
#   reports it as "The LDAP server is unavailable" in about twenty
#   milliseconds. That is a message about reachability for what is entirely a
#   question of trust, and the port is open the whole time.
#
# The key is made here and never leaves. Only the request travels.

set -euo pipefail

CERT=""
CHAIN=""
CSR_OUT="${CSR_OUT:-/tmp/ldap.csr}"
private=/var/lib/samba/private/tls

while [[ $# -gt 0 ]]; do
    case "$1" in
        --cert) CERT="$2"; shift 2 ;;
        --chain) CHAIN="$2"; shift 2 ;;
        --csr-out) CSR_OUT="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

[[ $EUID -eq 0 ]] || { echo "Run this with sudo." >&2; exit 2; }
command -v samba-tool >/dev/null || { echo "This is not a Samba DC." >&2; exit 3; }

fqdn="$(hostname -f)"
address="$(hostname -I | awk '{print $1}')"

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
note() { printf '  %s\n' "$*"; }

mkdir -p "$private"

# ------------------------------------------------------- pass one: a request

if [[ -z "$CERT" ]]; then
    say "a key and a request for $fqdn"

    if [[ ! -f "$private/ldap.key" ]]; then
        openssl genrsa -out "$private/ldap.key" 3072 2>/dev/null
        chmod 600 "$private/ldap.key"
        note "key written, readable by root only"
    else
        note "key already exists - reusing it, so the old request still matches"
    fi

    openssl req -new -key "$private/ldap.key" -sha256 \
        -subj "/CN=$fqdn/O=Blinky" -out "$CSR_OUT" 2>/dev/null

    chmod 644 "$CSR_OUT"

    cat <<EOF

  $CSR_OUT

Sign it where the CA lives, then come back with the result:

    scp $(hostname -s):$CSR_OUT .
    CA_PASSWORD=... bash scripts/sign-server-cert.sh \
        --csr ldap.csr --host $fqdn --host $address > ldap.crt
    scp ldap.crt chain.pem $(hostname -s):/tmp/
    sudo bash samba-ldap-tls.sh --cert /tmp/ldap.crt --chain /tmp/chain.pem

EOF
    exit 0
fi

# ---------------------------------------------------- pass two: install it

[[ -f "$CERT" ]] || { echo "No such certificate: $CERT" >&2; exit 2; }
[[ -f "$private/ldap.key" ]] || {
    echo "No key at $private/ldap.key - run this without --cert first." >&2
    exit 2
}

say "installing the LDAP certificate"

# The certificate has to match the key that is already here. Samba starts
# happily with a mismatched pair and then fails every TLS handshake, which
# looks exactly like the problem this script is fixing.
cert_mod="$(openssl x509 -in "$CERT" -noout -modulus | openssl sha256)"
key_mod="$(openssl rsa -in "$private/ldap.key" -noout -modulus 2>/dev/null | openssl sha256)"

[[ "$cert_mod" == "$key_mod" ]] || {
    echo "That certificate was not made for $private/ldap.key." >&2
    echo "Sign the request this script wrote, not an older one." >&2
    exit 4
}

install -m 644 "$CERT" "$private/ldap.crt"

if [[ -n "$CHAIN" ]]; then
    [[ -f "$CHAIN" ]] || { echo "No such chain: $CHAIN" >&2; exit 2; }
    install -m 644 "$CHAIN" "$private/ldap-ca.pem"
    note "chain installed"
elif [[ -f "$private/ca-chain.pem" ]]; then
    # blinky-samba-setup.sh has already put one here.
    install -m 644 "$private/ca-chain.pem" "$private/ldap-ca.pem"
    note "chain taken from the one blinky-samba-setup.sh installed"
else
    echo "No chain given and none found. A client cannot verify what it" >&2
    echo "cannot build a path to. Pass --chain." >&2
    exit 2
fi

note "cert    $private/ldap.crt"
note "key     $private/ldap.key"
note "ca      $private/ldap-ca.pem"

# ------------------------------------------------------------- tell Samba

say "smb.conf"

set_global() {
    local key="$1" value="$2"

    if grep -qE "^[[:space:]]*$key[[:space:]]*=" /etc/samba/smb.conf; then
        sed -i "s|^[[:space:]]*$key[[:space:]]*=.*|\t$key = $value|" /etc/samba/smb.conf
    else
        sed -i "/^\[global\]/a\\t$key = $value" /etc/samba/smb.conf
    fi

    note "$key = $value"
}

# "tls enabled" is on by default, but saying so costs nothing and removes a
# question from whoever reads this file later.
set_global "tls enabled" "yes"
set_global "tls certfile" "$private/ldap.crt"
set_global "tls keyfile"  "$private/ldap.key"
set_global "tls cafile"   "$private/ldap-ca.pem"

systemctl restart samba-ad-dc
sleep 5

# ---------------------------------------------------------------- check

say "what the listener presents now"

subject="$(echo | timeout 10 openssl s_client -connect "127.0.0.1:389" -starttls ldap 2>/dev/null |
    awk -F'subject=' '/^subject=/{print $2; exit}')"

if [[ -z "$subject" ]]; then
    echo "  StartTLS did not complete. Samba's log is in /var/log/samba/." >&2
    exit 5
fi

note "subject $subject"

case "$subject" in
    *"temporary autogenerated"*)
        echo
        echo "  Still the self-signed one. smb.conf was written but Samba did not" >&2
        echo "  take it - check /var/log/samba/ for a complaint about the files." >&2
        exit 5
        ;;
esac

verified="$(echo | timeout 10 openssl s_client -connect "127.0.0.1:389" -starttls ldap \
    -CAfile "$private/ldap-ca.pem" 2>/dev/null | awk '/Verify return code:/{print; exit}')"

note "${verified:-no verification result}"
