#!/usr/bin/env bash
#
# Blinky - sign an ordinary TLS server certificate with the built-in CA.
#
#     bash sign-server-cert.sh --csr ldap.csr --host by-dc01.blinky.lab
#     bash sign-server-cert.sh --csr ldap.csr --host by-dc01.blinky.lab --host 172.16.5.10
#
# Run on the machine holding ca/. Prints the certificate to stdout.
#
# The key stays where it was made. That is the whole point of taking a request
# rather than producing a key here and shipping it: a private key that travels
# has been in a pipe, a file and somebody's shell history, and none of those
# can be un-done afterwards. sign-kdc-cert.sh works the same way.
#
# What this is for, in this lab: Samba's LDAP listener. A fresh domain
# controller answers StartTLS with a certificate it generated for itself -
# "Samba - temporary autogenerated HOST certificate" - which nothing can
# verify. A client that checks, refuses; a client that does not check is
# sending a bind password to whoever answered. The failure reads as "The LDAP
# server is unavailable", which is a message about reachability for what is
# really a question of trust.

set -euo pipefail

cd "$(dirname "$0")/.."

CSR=""
PUBLIC_URL="${CA_PUBLIC_URL:-}"
CA_DIR="${CA_DIR:-ca}"
DAYS="${DAYS:-825}"
hosts=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --csr) CSR="$2"; shift 2 ;;
        --host) hosts+=("$2"); shift 2 ;;
        --public-url) PUBLIC_URL="$2"; shift 2 ;;
        --ca) CA_DIR="$2"; shift 2 ;;
        --days) DAYS="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

[[ -n "$CSR" && ${#hosts[@]} -gt 0 ]] || {
    echo "usage: sign-server-cert.sh --csr <file> --host <name> [--host <name-or-address>]" >&2
    exit 2
}

[[ -f "$CSR" ]] || { echo "No such request: $CSR" >&2; exit 2; }
[[ -f "$CA_DIR/issuing.p12" ]] || { echo "No issuing CA in $CA_DIR." >&2; exit 3; }
[[ -n "${CA_PASSWORD:-}" ]] || { echo "CA_PASSWORD is not set." >&2; exit 2; }

PUBLIC_URL="${PUBLIC_URL%/}"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

openssl pkcs12 -in "$CA_DIR/issuing.p12" -passin "pass:$CA_PASSWORD" \
    -nocerts -nodes -out "$work/issuing.key" 2>/dev/null || {
    echo "The issuing PKCS#12 would not open with CA_PASSWORD." >&2
    exit 4
}

# Names, including the short form. A Windows machine reaching a server by its
# NetBIOS name presents that name for verification, and a certificate carrying
# only the FQDN is refused for a reason that says nothing about names.
sans=()
for h in "${hosts[@]}"; do
    if [[ "$h" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        sans+=("IP:$h")
    else
        sans+=("DNS:$h")
        short="${h%%.*}"
        [[ "$short" != "$h" ]] && sans+=("DNS:$short")
    fi
done

san_list="$(IFS=,; echo "${sans[*]}")"

{
    echo "basicConstraints=critical,CA:FALSE"
    echo "keyUsage=critical,digitalSignature,keyEncipherment"
    echo "extendedKeyUsage=serverAuth"
    echo "subjectKeyIdentifier=hash"
    echo "authorityKeyIdentifier=keyid:always"
    echo "subjectAltName=$san_list"

    if [[ -n "$PUBLIC_URL" ]]; then
        echo "crlDistributionPoints=URI:$PUBLIC_URL/pki/issuing.crl"
        echo "authorityInfoAccess=caIssuers;URI:$PUBLIC_URL/pki/issuing.crt"
    fi
} > "$work/server.ext"

openssl x509 -req -in "$CSR" -days "$DAYS" \
    -CA "$CA_DIR/issuing.crt" -CAkey "$work/issuing.key" -CAcreateserial \
    -out "$work/server.crt" -extfile "$work/server.ext" 2>/dev/null

# Checked here, where a failure costs a line of output, rather than on the
# machine that installs it, where it costs a service that will not start.
openssl verify -CAfile "$CA_DIR/anchor.crt" -untrusted "$CA_DIR/issuing.crt" \
    "$work/server.crt" >/dev/null 2>&1 || {
    echo "The signed certificate does not chain to $CA_DIR/anchor.crt." >&2
    exit 5
}

# Names on stderr so stdout stays a certificate and can be redirected.
{
    echo "subject: $(openssl x509 -in "$work/server.crt" -noout -subject | sed 's/^subject=//')"
    echo "names:   $san_list"
    echo "expires: $(openssl x509 -in "$work/server.crt" -noout -enddate | cut -d= -f2-)"
} >&2

cat "$work/server.crt"
