<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Blinky.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Attestation\yubico-piv-attestation-root.pem" />
    <EmbeddedResource Include="Attestation\yubico-attestation-root-1.pem" />
    <EmbeddedResource Include="Attestation\yubico-piv-attestation-intermediates.pem" />
  </ItemGroup>

</Project>
